name: Package exe with PyInstaller - Windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        mkdir -p src
        mv pyinstaller-win10/modify_lastname.spec src/
        mv modify_lastname.py src/
    - name: PyInstaller Windows
      uses: JackMcKew/pyinstaller-action-windows@python3-10-pyinstaller-5-3
      with:
        path: src
    - run: |
        mkdir release
        mv names.txt data/* src/dist/windows/* release/
        mv pyinstaller-win10/cli-wrapper.cs release/
    - uses: actions/upload-artifact@v2
      with:
        name: modify-lastname
        path: release