name: Build

on:
  workflow_call:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: |
        mkdir -p src
        mv pyinstaller-win10/modify_lastname.spec src/
        mv modify_lastname.py src/
    - name: PyInstaller Windows
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: src
    - run: |
        mkdir release
        mv names.txt data/* src/dist/windows/* release/
        mv pyinstaller-win10/cli-wrapper.ps1 release/
    - uses: actions/upload-artifact@v3
      with:
        name: modify-lastname
        path: release/*
