name: Release

on:
  push:
    tags:
      - v*

jobs:
  build:
    uses: ./.github/workflows/pyinstaller.yml
  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download
        uses: actions/download-artifact@v3
        with:
          name: modify-lastname
          path: release
      - name: zip release
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r release.zip . -i release/*
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body: |
            Release:
            - src: contains source. use this if you can run python through cmdline
            - release.zip: for windows10 convenience, it contains a single .exe and .ps1 wrapper to select .bin
          files: |
            release.zip