name: Release

on:
  push:
    tags:
      - v*

jobs:
  build:
    uses: ./.github/workflows/pyinstaller.yml
  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          sparse-checkout: |
            .github
      - name: Download
        uses: actions/download-artifact@v3
        with:
          name: modify-lastname
          path: release
      - name: zip release
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r release.zip . -i release/*
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: ".github/workflow_data/release.md"
          files: |
            release.zip